; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/adafruit/DHT-sensor-library.git
    miguelbalboa/MFRC522@^1.4.10
    https://github.com/knolleary/pubsubclient.git

; Use a partition table with bigger app space
board_build.partitions = huge_app.csv          ; ← this is usually enough (~3 MB app)
; or even bigger if needed:
; board_build.partitions = min_spiffs.csv      ; ~3 MB app, very small spiffs
; board_build.partitions = no_ota.csv          ; ~3.1 MB app, no OTA

; Optional: reduce some debug output / optimize size
build_flags =
    -Os                                 ; optimize for size
    -DCORE_DEBUG_LEVEL=0                ; disable most debug prints (saves ~10–30 kB)

